export const officialSourceDomains = [
  "fff.fr", "fifa.com", "uefa.com", "ligue1.fr", "lfp.fr",
  "psg.fr", "om.fr", "ol.fr", "asmonaco.com", "losc.fr", "rclens.fr",
  "realmadrid.com", "fcbarcelona.com", "mancity.com", "manutd.com", "liverpoolfc.com",
  "arsenal.com", "chelseafc.com", "fcbayern.com", "bvb.de", "juventus.com", "inter.it", "acmilan.com",
  "toulousefc.com", "hac-foot.com", "angers-sco.fr", "fcmetz.com", "stade-de-reims.com",
  "parisfc.fr", "fc-lorient.com", "asse.fr", "smcaen.fr",
  "villarrealcf.es", "sevillafc.es", "realbetisbalompie.es", "athletic-club.eus", "valenciacf.com",
  "whufc.com", "avfc.co.uk", "brightonandhovealbion.com", "evertonfc.com", "wolves.co.uk",
  "atalanta.it", "acffiorentina.com", "sslazio.it", "torinofc.it",
  "eintracht.de", "fc-union-berlin.de", "vfl-wolfsburg.de", "scbraga.pt",
  "celticfc.com", "rangers.co.uk", "olympiacos.org",
];

export const recognizedSourceDomains = [
  "lequipe.fr", "rmcsport.bfmtv.com", "eurosport.fr", "franceinfo.fr", "francetvinfo.fr",
  "lemonde.fr", "lefigaro.fr", "ouest-france.fr", "20minutes.fr", "footmercato.net",
  "sofoot.com", "goal.com", "beinsports.com", "francebleu.fr", "radiofrance.fr",
  "foot-national.com", "onzemondial.com", "real-france.fr", "mercatofootanglais.com",
  "parisfans.fr", "allezpaillade.com", "lephoceen.fr", "espritgones.fr",
];

export const suspiciousImagePattern = /(logo|favicon|avatar|author|profile|placeholder|default|fallback|sprite|blank|transparent|tracking[_-]?pixel)/i;

export const titleStopWords = new Set([
  "a", "au", "aux", "avec", "ce", "ces", "dans", "de", "des", "du", "elle", "en", "et",
  "est", "il", "la", "le", "les", "mais", "ne", "ou", "par", "pas", "pour", "que", "qui",
  "se", "son", "sur", "un", "une", "vers", "mercato", "football", "foot", "transfert", "transferts",
]);

export const footballPattern = /\b(football|foot|soccer|mercato|transferts?|ligue [12]|ligue des champions|champions league|premier league|la ?liga|serie a|bundesliga|europa league|ligue europa|conference league|coupe du monde|mondial des clubs|euro 20\d{2}|can 20\d{2}|fegafoot|psg|paris saint-germain|montpellier fc|bar[çc]a|barcelone|real madrid|arsenal|liverpool|chelsea|juventus|bayern|manchester city|manchester united|fenerbah[çc]e)\b/i;
export const clubAcronymPattern = /(?:^|[^\p{L}\p{N}])(OM|OL)(?=$|[^\p{L}\p{N}])/u;
export const excludedPattern = /\b(euromillions?|keno|loto|fdj|paris sportifs?|casino|jackpot|tirage gagnant|guide achat|code promo|streaming gratuit|marijuana|cocaïne|drogues?)\b/i;
export const excludedURLPattern = /\/(guide-achat|bons-plans|pronostics?|paris-sportifs?)\//i;
export const rumorPattern = /\b(rumeurs?|gossip|pourrait|piste|vise|cible|intérêt|proche de|pressenti|vers (un|le) départ)\b/i;
export const transferPattern = /\b(transferts?|mercato|signe|signé|prêt|recrue|recrute|rejoint|quitte|départ|accord|engage|officialise|officiel)\b|s[’']offre/i;
export const officialPattern = /\b(officiel|officialisé|confirmé|a signé|annonce|communiqué)\b/i;

export const teamAliases = [
  ["psg", ["psg", "paris saint-germain"]],
  ["om", ["olympique de marseille", "marseille"]],
  ["ol", ["olympique lyonnais", "lyon"]],
  ["monaco", ["as monaco", "monaco"]],
  ["lille", ["losc", "lille"]],
  ["lens", ["rc lens", "lens"]],
  ["rennes", ["stade rennais", "rennes"]],
  ["nice", ["ogc nice", "nice"]],
  ["nantes", ["fc nantes", "nantes"]],
  ["strasbourg", ["rc strasbourg", "strasbourg"]],
  ["brest", ["stade brestois", "brest"]],
  ["auxerre", ["aj auxerre", "auxerre"]],
  ["montpellier", ["montpellier hsc", "montpellier hérault sc", "montpellier"]],
  ["real-madrid", ["real madrid"]],
  ["barcelona", ["fc barcelone", "barcelone", "barça"]],
  ["atletico", ["atlético de madrid", "atletico madrid"]],
  ["man-city", ["manchester city", "man city"]],
  ["man-united", ["manchester united", "man united"]],
  ["liverpool", ["liverpool"]],
  ["arsenal", ["arsenal"]],
  ["chelsea", ["chelsea"]],
  ["tottenham", ["tottenham", "spurs"]],
  ["newcastle", ["newcastle"]],
  ["bayern", ["bayern munich"]],
  ["dortmund", ["borussia dortmund", "dortmund"]],
  ["leverkusen", ["bayer leverkusen", "leverkusen"]],
  ["juventus", ["juventus", "juve"]],
  ["inter", ["inter milan", "internazionale"]],
  ["ac-milan", ["ac milan"]],
  ["napoli", ["napoli", "naples"]],
  ["roma", ["as roma", "roma"]],
  ["benfica", ["benfica"]],
  ["porto", ["fc porto", "porto"]],
  ["sporting", ["sporting cp", "sporting portugal"]],
  ["ajax", ["ajax amsterdam", "ajax"]],
  ["feyenoord", ["feyenoord"]],
  ["psv", ["psv eindhoven", "psv"]],
  ["galatasaray", ["galatasaray"]],
  ["fenerbahce", ["fenerbahçe", "fenerbahce"]],
  ["al-hilal", ["al-hilal", "al hilal"]],
  ["inter-miami", ["inter miami"]],
  ["toulouse", ["toulouse fc", "toulouse"]],
  ["le-havre", ["le havre ac", "le havre"]],
  ["angers", ["angers sco", "angers"]],
  ["metz", ["fc metz", "metz"]],
  ["reims", ["stade de reims", "reims"]],
  ["paris-fc", ["paris fc"]],
  ["lorient", ["fc lorient", "lorient"]],
  ["saint-etienne", ["as saint-étienne", "saint-étienne", "asse"]],
  ["bordeaux", ["girondins de bordeaux", "bordeaux"]],
  ["guingamp", ["ea guingamp", "guingamp"]],
  ["caen", ["sm caen", "caen"]],
  ["clermont", ["clermont foot", "clermont"]],
  ["ajaccio", ["ac ajaccio", "ajaccio"]],
  ["real-sociedad", ["real sociedad"]],
  ["villarreal", ["villarreal"]],
  ["sevilla", ["séville fc", "séville"]],
  ["real-betis", ["real betis"]],
  ["athletic-bilbao", ["athletic bilbao", "athletic club"]],
  ["valencia", ["valencia cf", "fc valence"]],
  ["west-ham", ["west ham united", "west ham"]],
  ["aston-villa", ["aston villa"]],
  ["brighton", ["brighton & hove albion", "brighton"]],
  ["everton", ["everton"]],
  ["wolves", ["wolverhampton wanderers", "wolves"]],
  ["atalanta", ["atalanta"]],
  ["fiorentina", ["fiorentina"]],
  ["lazio", ["lazio rome", "lazio"]],
  ["torino", ["torino fc", "torino"]],
  ["rb-leipzig", ["rb leipzig"]],
  ["eintracht-frankfurt", ["eintracht francfort", "eintracht frankfurt"]],
  ["union-berlin", ["union berlin"]],
  ["wolfsburg", ["vfl wolfsbourg", "wolfsburg"]],
  ["braga", ["sc braga", "braga"]],
  ["al-nassr", ["al-nassr", "al nassr"]],
  ["al-ittihad", ["al-ittihad", "al ittihad"]],
  ["al-ahli", ["al-ahli saoudien", "al-ahli"]],
  ["la-galaxy", ["los angeles galaxy", "la galaxy"]],
  ["celtic", ["celtic fc", "celtic glasgow"]],
  ["rangers", ["rangers fc", "glasgow rangers"]],
  ["olympiacos", ["olympiacos"]],
  ["troyes", ["estac troyes", "troyes"]],
  ["nancy", ["as nancy-lorraine", "nancy"]],
  ["amiens", ["amiens sc", "amiens"]],
  ["valenciennes", ["valenciennes fc", "valenciennes"]],
  ["grenoble", ["grenoble foot 38", "grenoble"]],
  ["laval", ["stade lavallois", "laval"]],
  ["annecy", ["fc annecy", "annecy"]],
  ["dunkerque", ["usl dunkerque", "dunkerque"]],
  ["pau", ["pau fc", "pau"]],
  ["rodez", ["rodez aveyron football", "rodez"]],
  ["red-star", ["red star fc", "red star"]],
  ["martigues", ["fc martigues", "martigues"]],
  ["concarneau", ["us concarneau", "concarneau"]],
  ["le-mans", ["le mans fc", "le mans"]],
  ["boulogne", ["us boulogne", "boulogne"]],
  ["bournemouth", ["afc bournemouth", "bournemouth"]],
  ["brentford", ["brentford fc", "brentford"]],
  ["burnley", ["burnley fc", "burnley"]],
  ["crystal-palace", ["crystal palace fc", "crystal palace"]],
  ["fulham", ["fulham fc", "fulham"]],
  ["leeds", ["leeds united", "leeds"]],
  ["nottingham-forest", ["nottingham forest"]],
  ["sunderland", ["sunderland afc", "sunderland"]],
  ["leicester", ["leicester city", "leicester"]],
  ["southampton", ["southampton fc", "southampton"]],
  ["ipswich", ["ipswich town", "ipswich"]],
  ["norwich", ["norwich city", "norwich"]],
  ["west-brom", ["west bromwich albion", "west brom"]],
  ["middlesbrough", ["middlesbrough fc", "middlesbrough"]],
  ["sheffield-united", ["sheffield united"]],
  ["sheffield-wednesday", ["sheffield wednesday"]],
  ["stoke", ["stoke city", "stoke"]],
  ["coventry", ["coventry city", "coventry"]],
  ["watford", ["watford fc", "watford"]],
  ["hull", ["hull city", "hull"]],
  ["preston", ["preston north end", "preston"]],
  ["millwall", ["millwall fc", "millwall"]],
  ["blackburn", ["blackburn rovers", "blackburn"]],
  ["swansea", ["swansea city", "swansea"]],
  ["cardiff", ["cardiff city", "cardiff"]],
  ["derby", ["derby county", "derby"]],
  ["bristol-city", ["bristol city"]],
  ["qpr", ["queens park rangers", "qpr"]],
  ["portsmouth", ["portsmouth fc", "portsmouth"]],
  ["oxford-united", ["oxford united"]],
  ["wrexham", ["wrexham afc", "wrexham"]],
  ["charlton", ["charlton athletic", "charlton"]],
  ["bolton", ["bolton wanderers", "bolton"]],
  ["reading", ["reading fc", "reading"]],
  ["wigan", ["wigan athletic", "wigan"]],
  ["barnsley", ["barnsley fc", "barnsley"]],
  ["celta-vigo", ["celta de vigo", "celta vigo"]],
  ["espanyol", ["rcd espanyol", "espanyol"]],
  ["getafe", ["getafe cf", "getafe"]],
  ["girona", ["girona fc", "girona"]],
  ["mallorca", ["rcd mallorca", "mallorca"]],
  ["osasuna", ["ca osasuna", "osasuna"]],
  ["rayo-vallecano", ["rayo vallecano"]],
  ["alaves", ["deportivo alavés", "alavés"]],
  ["las-palmas", ["ud las palmas", "las palmas"]],
  ["real-zaragoza", ["real zaragoza"]],
  ["deportivo", ["deportivo la corogne", "deportivo la coruña"]],
  ["sporting-gijon", ["sporting de gijón", "sporting gijón"]],
  ["racing-santander", ["racing de santander"]],
  ["malaga", ["málaga cf", "malaga"]],
  ["cadiz", ["cádiz cf", "cadix"]],
  ["almeria", ["ud almería", "almería"]],
  ["eibar", ["sd eibar", "eibar"]],
  ["huesca", ["sd huesca", "huesca"]],
  ["albacete", ["albacete balompié"]],
  ["burgos", ["burgos cf", "burgos"]],
  ["monchengladbach", ["borussia mönchengladbach", "mönchengladbach"]],
  ["stuttgart", ["vfb stuttgart", "stuttgart"]],
  ["freiburg", ["sc fribourg", "sc freiburg"]],
  ["werder-bremen", ["werder brême", "werder bremen"]],
  ["mainz", ["fsv mayence 05", "mainz 05"]],
  ["hoffenheim", ["tsg hoffenheim", "hoffenheim"]],
  ["augsburg", ["fc augsbourg", "augsburg"]],
  ["bochum", ["vfl bochum", "bochum"]],
  ["heidenheim", ["fc heidenheim", "heidenheim"]],
  ["holstein-kiel", ["holstein kiel"]],
  ["st-pauli", ["fc st. pauli", "st pauli"]],
  ["hamburg", ["hambourg sv", "hamburger sv"]],
  ["hertha", ["hertha bsc", "hertha berlin"]],
  ["schalke", ["schalke 04", "fc schalke"]],
  ["fortuna-dusseldorf", ["fortuna düsseldorf"]],
  ["hannover", ["hannover 96"]],
  ["karlsruhe", ["karlsruher sc"]],
  ["nurnberg", ["1. fc nuremberg", "fc nuremberg"]],
  ["kaiserslautern", ["1. fc kaiserslautern", "kaiserslautern"]],
  ["paderborn", ["sc paderborn 07", "paderborn"]],
  ["braunschweig", ["eintracht brunswick", "braunschweig"]],
  ["elversberg", ["sv elversberg"]],
  ["bologna", ["bologna fc", "bologne"]],
  ["udinese", ["udinese calcio", "udinese"]],
  ["genoa", ["genoa cfc", "genoa"]],
  ["cagliari", ["cagliari calcio", "cagliari"]],
  ["verona", ["hellas vérone", "hellas verona"]],
  ["parma", ["parma calcio", "parme"]],
  ["como", ["como 1907", "como"]],
  ["cremonese", ["us cremonese", "cremonese"]],
  ["sassuolo", ["us sassuolo", "sassuolo"]],
  ["pisa", ["pisa sc", "pisa"]],
  ["lecce", ["us lecce", "lecce"]],
  ["palermo", ["palermo fc", "palerme"]],
  ["bari", ["ssc bari", "bari"]],
  ["sampdoria", ["uc sampdoria", "sampdoria"]],
  ["venezia", ["venezia fc", "venise"]],
  ["catanzaro", ["us catanzaro"]],
  ["cesena", ["cesena fc"]],
  ["modena", ["modena fc"]],
  ["reggiana", ["ac reggiana 1919", "reggiana"]],
  ["spezia", ["spezia calcio"]],
  ["frosinone", ["frosinone calcio"]],
  ["vitoria-guimaraes", ["vitória sport clube", "vitória guimarães"]],
  ["boavista", ["boavista fc"]],
  ["famalicao", ["fc famalicão"]],
  ["estoril", ["gd estoril praia", "estoril"]],
  ["casa-pia", ["casa pia ac"]],
  ["gil-vicente", ["gil vicente fc"]],
  ["moreirense", ["moreirense fc"]],
  ["arouca", ["fc arouca"]],
  ["rio-ave", ["rio ave fc"]],
  ["santa-clara", ["cd santa clara"]],
  ["az-alkmaar", ["az alkmaar"]],
  ["twente", ["fc twente"]],
  ["utrecht", ["fc utrecht"]],
  ["sparta-rotterdam", ["sparta rotterdam"]],
  ["go-ahead-eagles", ["go ahead eagles"]],
  ["nec-nijmegen", ["nec nimègue", "nec nijmegen"]],
  ["heerenveen", ["sc heerenveen"]],
  ["fortuna-sittard", ["fortuna sittard"]],
  ["willem-ii", ["willem ii tilburg", "willem ii"]],
  ["pec-zwolle", ["pec zwolle"]],
  ["club-brugge", ["club bruges", "club brugge"]],
  ["anderlecht", ["rsc anderlecht"]],
  ["genk", ["krc genk"]],
  ["standard-liege", ["standard de liège"]],
  ["union-saint-gilloise", ["union saint-gilloise"]],
  ["gent", ["kaa gand", "kaa gent"]],
  ["antwerp", ["royal antwerp fc", "antwerp fc"]],
  ["charleroi", ["sporting charleroi"]],
  ["cercle-brugge", ["cercle bruges", "cercle brugge"]],
  ["mechelen", ["kv malines", "kv mechelen"]],
  ["kortrijk", ["kv courtrai", "kv kortrijk"]],
  ["oh-leuven", ["oud-heverlee louvain", "oh leuven"]],
  ["westerlo", ["kvc westerlo"]],
  ["st-truiden", ["stvv", "sint-truidense"]],
  ["flamengo", ["clube de regatas do flamengo", "flamengo"]],
  ["palmeiras", ["sociedade esportiva palmeiras", "palmeiras"]],
  ["sao-paulo", ["são paulo fc", "sao paulo fc"]],
  ["corinthians", ["sport club corinthians paulista", "corinthians"]],
  ["santos", ["santos fc"]],
  ["gremio", ["grêmio foot-ball porto alegrense", "grêmio"]],
  ["internacional", ["sport club internacional"]],
  ["cruzeiro", ["cruzeiro esporte clube"]],
  ["atletico-mineiro", ["clube atlético mineiro", "atlético mineiro"]],
  ["fluminense", ["fluminense football club"]],
  ["botafogo", ["botafogo de futebol e regatas"]],
  ["vasco-da-gama", ["club de regatas vasco da gama", "vasco da gama"]],
  ["bahia", ["esporte clube bahia"]],
  ["fortaleza", ["fortaleza esporte clube"]],
];

export const competitionAliases = [
  ["ligue-1", ["ligue 1"]],
  ["ligue-2", ["ligue 2"]],
  ["premier-league", ["premier league"]],
  ["la-liga", ["laliga", "la liga"]],
  ["serie-a", ["serie a"]],
  ["bundesliga", ["bundesliga"]],
  ["liga-portugal", ["liga portugal"]],
  ["eredivisie", ["eredivisie"]],
  ["champions-league", ["ligue des champions", "champions league"]],
  ["europa-league", ["ligue europa", "europa league"]],
  ["conference-league", ["ligue conférence", "conference league"]],
  ["club-world-cup", ["mondial des clubs", "coupe du monde des clubs"]],
  ["coupe-de-france", ["coupe de france"]],
  ["world-cup", ["coupe du monde de football", "coupe du monde"]],
  ["afcon", ["coupe d'afrique des nations"]],
  ["copa-america", ["copa america"]],
  ["saudi-pro-league", ["saudi pro league", "championnat saoudien"]],
  ["mls", ["major league soccer"]],
  ["liga-mx", ["liga mx"]],
  ["championship", ["championship anglais", "efl championship"]],
  ["segunda-division", ["segunda división", "deuxième division espagnole"]],
  ["serie-b", ["serie b", "deuxième division italienne"]],
  ["2-bundesliga", ["2. bundesliga", "deuxième division allemande"]],
  ["belgian-pro-league", ["jupiler pro league", "pro league belge"]],
  ["brasileirao", ["brasileirão", "brasileirao", "championnat du brésil"]],
  ["ligue-3", ["ligue 3", "championnat national de football"]],
];

// Plusieurs compétitions étrangères portent le même nom qu'une compétition
// européenne suivie par l'app ("Ligue 1" en Algérie/Tunisie/Cameroun, "Serie A"
// au Brésil, "Bundesliga" en Autriche). Un simple test de sous-chaîne les
// confondrait avec la compétition française/italienne/allemande : ce filtre
// annule le tag si le titre mentionne explicitement le pays étranger concerné.
export const competitionDisambiguators = {
  "ligue-1": /\b(algérie|algérienne|algérien|tunisie|tunisienne|tunisien|maroc|marocaine|marocain|cameroun|camerounaise|camerounais|côte d'ivoire|ivoirienne|ivoirien|sénégal|sénégalaise|sénégalais|mali|malienne|malien|guinée|guinéenne|guinéen|bénin|béninoise|béninois|togo|togolaise|togolais|gabon|gabonaise|gabonais|burkina|burkinabè|congo|congolaise|congolais|haïti|haïtienne|haïtien|québec|québécoise|québécois)\b/i,
  "ligue-2": /\b(algérie|algérienne|algérien|tunisie|tunisienne|tunisien|maroc|marocaine|marocain|cameroun|camerounaise|camerounais)\b/i,
  "serie-a": /\b(brésil|brésilienne|brésilien|bresil|paulista|carioca)\b/i,
  "serie-b": /\b(brésil|brésilienne|brésilien|bresil|paulista|carioca)\b/i,
  "bundesliga": /\b(autriche|autrichienne|autrichien)\b/i,
};

export const nationAliases = [
  ["france", ["équipe de france", "bleus", "les bleues"]],
  ["belgium", ["équipe de belgique", "diables rouges"]],
  ["switzerland", ["équipe de suisse", "nati"]],
  ["morocco", ["équipe du maroc", "lions de l'atlas"]],
  ["algeria", ["équipe d'algérie", "fennecs"]],
  ["senegal", ["équipe du sénégal", "lions de la teranga"]],
  ["ivory-coast", ["équipe de côte d'ivoire", "éléphants"]],
  ["cameroon", ["équipe du cameroun", "lions indomptables"]],
  ["england", ["équipe d'angleterre", "three lions"]],
  ["spain", ["équipe d'espagne", "la roja"]],
  ["italy", ["équipe d'italie", "squadra azzurra"]],
  ["germany", ["équipe d'allemagne", "mannschaft"]],
  ["portugal", ["équipe du portugal", "seleção portugaise"]],
  ["netherlands", ["équipe des pays-bas", "oranje"]],
  ["brazil", ["équipe du brésil", "seleção brésilienne"]],
  ["argentina", ["équipe d'argentine", "albiceleste"]],
  ["uruguay", ["équipe d'uruguay", "celeste"]],
  ["usa", ["équipe des états-unis", "team usa"]],
  ["japan", ["équipe du japon", "samurai blue"]],
  ["south-korea", ["équipe de corée du sud"]],
  ["egypt", ["équipe d'égypte", "pharaons"]],
  ["nigeria", ["équipe du nigeria", "super eagles"]],
  ["ghana", ["équipe du ghana", "black stars"]],
  ["tunisia", ["équipe de tunisie", "aigles de carthage"]],
  ["mali", ["équipe du mali", "aigles du mali"]],
  ["colombia", ["équipe de colombie", "cafeteros"]],
  ["chile", ["équipe du chili"]],
  ["mexico", ["équipe du mexique", "el tri"]],
  ["croatia", ["équipe de croatie", "vatreni"]],
  ["poland", ["équipe de pologne"]],
  ["wales", ["équipe du pays de galles"]],
  ["scotland", ["équipe d'écosse"]],
  ["turkey", ["équipe de turquie"]],
  ["qatar", ["équipe du qatar"]],
  ["saudi-arabia", ["équipe d'arabie saoudite"]],
  ["ecuador", ["équipe d'équateur"]],
  ["denmark", ["équipe du danemark"]],
  ["sweden", ["équipe de suède"]],
  ["serbia", ["équipe de serbie"]],
  ["ukraine", ["équipe d'ukraine"]],
];

// Nom officiel/complet de chaque club, compétition et sélection déjà cataloguée
// ci-dessus, utilisé pour détecter qu'un titre parle de football même sans les
// mots génériques ("football", "mercato"...). On prend la première variante de
// chaque entrée : elle est toujours la plus explicite (jamais un simple nom de
// ville ou de pays isolé), pour éviter les faux positifs.
export const topicGatePhrases = [
  ...teamAliases.map(([, aliases]) => aliases[0]),
  ...competitionAliases.map(([, aliases]) => aliases[0]),
  ...nationAliases.map(([, aliases]) => aliases[0]),
];
